source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/rinat-enikeev/CocoaPodsSpecs.git'

use_frameworks!

target 'InstaKit_Example', :exclusive => true do
  pod "InstaKit", :path => "../"
  pod 'STXInstagramFeedView'
  pod 'Reachability'
  pod 'TSMessages', :git => 'https://github.com/KrauseFx/TSMessages.git'
end

target 'InstaKit_Tests', :exclusive => true do
  pod "InstaKit", :path => "../"

  pod 'InstaModel'

  pod 'Specta'
  pod 'Expecta'
  
end
